// preview.component.ts
import { Component, ElementRef, ViewChild, AfterViewInit, Input, OnChanges, SimpleChanges, inject } from '@angular/core';
import sdk, { VM } from '@stackblitz/sdk';
import { LoaderService } from '../../../../shared/services/loader.service';

@Component({
  selector: 'app-live-preview',
  template: `<div id="previewContainer" #previewContainer style="height:50vh"></div>`,
  standalone: true
})
export class LivePreviewComponent implements AfterViewInit, OnChanges {
  @ViewChild('previewContainer', { static: true }) container!: ElementRef;
  @Input() generatedFiles: Record<string, string> | null = null;

  private hasInitialized = false;
  private embeddedVM: VM | null = null;
  private lastPackageJson = '';
  private loaderService = inject(LoaderService);

  async ngAfterViewInit() {
    this.hasInitialized = true;
    this.initializePreview();
  }

  ngOnChanges(changes: SimpleChanges) {
    // Detect input changes and re-render StackBlitz
    if (changes['generatedFiles'] && this.hasInitialized && !changes['generatedFiles'].firstChange && this.embeddedVM) {
      console.log('[LivePreview] generatedFiles changed, re-initializing StackBlitz...');
      const nextPackageJson = this.generatedFiles?.['package.json'] || '';
      if (nextPackageJson !== this.lastPackageJson) {
        this.initializePreview();
        return;
      }
      this.embeddedVM.applyFsDiff({
        create: this.generatedFiles || {},
        destroy: []
      })
    }
  }

  /**
   * Extracts project dependencies from the generated files' package.json
   * Includes both dependencies and devDependencies (needed for tools like Tailwind)
   */
  private extractDependencies(files: Record<string, string>): Record<string, string> {
    try {
      // Check if package.json exists in the generated files
      if (files['package.json']) {
        const packageJson = JSON.parse(files['package.json']);
        const deps = packageJson.dependencies || {};
        const devDeps = packageJson.devDependencies || {};
        // StackBlitz's SDK dependency map is flat, so include both runtime and build-time packages.
        return { ...deps, ...devDeps };
      }
    } catch (error) {
      console.warn('[LivePreview] Failed to parse package.json from generated files:', error);
    }

    // Fallback to default Angular 17 dependencies
    return {
      '@angular/animations': '^17.0.0',
      '@angular/common': '^17.0.0',
      '@angular/compiler': '^17.0.0',
      '@angular/core': '^17.0.0',
      '@angular/forms': '^17.0.0',
      '@angular/platform-browser': '^17.0.0',
      '@angular/platform-browser-dynamic': '^17.0.0',
      'rxjs': '~7.8.0',
      'tslib': '^2.3.0',
      'zone.js': '~0.14.2'
    };
  }

  private async initializePreview() {
    try {
      this.loaderService.startWithMessages([
        'Preparing live preview...',
        'Installing dependencies...',
        'Starting StackBlitz...',
      ]);
      this.container.nativeElement.innerHTML = '';
      let files = this.generatedFiles || {};
      this.lastPackageJson = files['package.json'] || '';

      // Extract dependencies from files
      const dependencies = this.extractDependencies(files);
      
      // Embed StackBlitz and store VM reference
      this.embeddedVM = await sdk.embedProject(this.container.nativeElement, {
        title: 'Angular Live Preview',
        description: 'Generated by ProtoPilot',
        template: 'angular-cli',
        files,
        dependencies,
        settings: {
          compile: { 
            action: 'hmr', 
            clearConsole: false,
            trigger: 'auto',

          },
        }
      }, {
        openFile: 'src/app/app.component.ts',
        view: 'preview',
        height: '100%',
      });     
      console.log('[LivePreview] StackBlitz initialized successfully with dependencies:', dependencies);
    } catch (error) {
      console.error('[LivePreview] Error initializing StackBlitz:', error);
    } finally {
      this.loaderService.stop();
    }
  }

}
